import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased pt-16 pb-20 min-h-screen bg-gradient-to-br from-[#00E5FF] via-[#E9EEF3] to-[#F3F4F6] bg-fixed`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
